// <auto-generated />
using System;
using Gma.Modules.AccessControl.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gma.Modules.AccessControl.Persistence.PostgreSqlMigrations.Migrations
{
    [DbContext(typeof(AccessControlDbContext))]
    [Migration("20260709130219_InitialAccessControlSchema")]
    partial class InitialAccessControlSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("access")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessPrincipal", b =>
                {
                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Kind", "SubjectId");

                    b.ToTable("principals", "access");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", "access");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessRolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "PermissionCode")
                        .IsUnique();

                    b.ToTable("role_permissions", "access");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessSubjectRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScopeValue")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("Scope");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("SubjectKind")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("SubjectKind", "SubjectId", "ScopeValue");

                    b.HasIndex("SubjectKind", "SubjectId", "RoleId", "ScopeValue")
                        .IsUnique();

                    b.ToTable("subject_role_assignments", "access");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessRolePermission", b =>
                {
                    b.HasOne("Gma.Modules.AccessControl.Persistence.Entities.AccessRole", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessSubjectRoleAssignment", b =>
                {
                    b.HasOne("Gma.Modules.AccessControl.Persistence.Entities.AccessRole", "Role")
                        .WithMany("Assignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gma.Modules.AccessControl.Persistence.Entities.AccessPrincipal", null)
                        .WithMany()
                        .HasForeignKey("SubjectKind", "SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessRole", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
