<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Gma.Modules.AccessControl.Contracts\Gma.Modules.AccessControl.Contracts.csproj" />
    <ProjectReference Include="$(GmaFrameworkRoot)Administration\Gma.Framework.Administration\Gma.Framework.Administration.csproj" />
  </ItemGroup>
</Project>
