// <auto-generated />
using System;
using Gma.Modules.AccessControl.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gma.Modules.AccessControl.Persistence.SqlServerMigrations.Migrations
{
    [DbContext(typeof(AccessControlDbContext))]
    [Migration("20260804051411_AddAccessControlScopeLifecycle")]
    partial class AddAccessControlScopeLifecycle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("access")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gma.Framework.Messaging.Infrastructure.InboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Handler")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Attempts")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("FailedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastError")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ProcessingStartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ScopeId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("ScopeId");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id", "Handler");

                    b.HasIndex("Handler", "Status");

                    b.HasIndex("Status", "ProcessedAtUtc");

                    b.ToTable("inbox_messages", "access");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Domain.Aggregates.AccessProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("CreatedByKind")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("LastChangedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastChangedById")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("LastChangedByKind")
                        .HasColumnType("int");

                    b.Property<string>("OwnerScopeValue")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("OwnerScope");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OwnerScopeValue", "Key")
                        .IsUnique();

                    b.HasIndex("OwnerScopeValue", "Status", "Key");

                    b.ToTable("access_profiles", "access");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Domain.Entities.AccessProfileAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AssignmentScopeValue")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("AssignmentScope");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("CreatedByKind")
                        .HasColumnType("int");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SubjectKind")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "SubjectKind", "SubjectId", "AssignmentScopeValue")
                        .IsUnique();

                    b.HasIndex("SubjectKind", "SubjectId", "AssignmentScopeValue", "ProfileId");

                    b.ToTable("access_profile_assignments", "access");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Domain.Entities.AccessProfileChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ActorKind")
                        .HasColumnType("int");

                    b.Property<string>("AssignmentScopeValue")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("AssignmentScope");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("ProfileVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("SubjectKind")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "OccurredAtUtc", "Id");

                    b.ToTable("access_profile_changes", "access");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Domain.Entities.AccessProfilePermission", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PermissionCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("ProfileId", "PermissionCode");

                    b.HasIndex("PermissionCode");

                    b.ToTable("access_profile_permissions", "access");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessBootstrapState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ClaimedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("ManagementRevision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("bootstrap_state", "access");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ManagementRevision = 0L
                        });
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessControlScopeDestroyOperation", b =>
                {
                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BatchSize")
                        .HasColumnType("int");

                    b.Property<int>("CompletedBatchCount")
                        .HasColumnType("int");

                    b.Property<long>("ExpectedRevision")
                        .HasColumnType("bigint");

                    b.Property<int>("ProofVersion")
                        .HasColumnType("int");

                    b.Property<string>("RemovalProofSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<long>("RemovedRecordCount")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<long>("ResultingRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("ScopeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("ScopeValue")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<int>("Stage")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TransportScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("OperationId");

                    b.HasIndex("ScopeHash")
                        .IsUnique();

                    b.ToTable("access_scope_destroy_operations", "access", t =>
                        {
                            t.HasCheckConstraint("CK_access_scope_destroy_operations_progress", "\"RemovedRecordCount\" >= 0 AND \"CompletedBatchCount\" >= 0");

                            t.HasCheckConstraint("CK_access_scope_destroy_operations_revisions", "\"ExpectedRevision\" >= 0 AND \"ResultingRevision\" > \"ExpectedRevision\"");
                        });
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessControlScopeDestroyPrincipalCandidate", b =>
                {
                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SubjectKind")
                        .HasColumnType("int");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("OperationId", "SubjectKind", "SubjectId");

                    b.ToTable("access_scope_destroy_principal_candidates", "access");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessControlScopeDestroyReceipt", b =>
                {
                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BatchSize")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("CompletedBatchCount")
                        .HasColumnType("int");

                    b.Property<long>("ExpectedRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("RemovalProofSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<int>("RemovalProofVersion")
                        .HasColumnType("int");

                    b.Property<long>("RemovedRecordCount")
                        .HasColumnType("bigint");

                    b.Property<string>("RequestSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<long>("ResultingRevision")
                        .HasColumnType("bigint");

                    b.Property<string>("ScopeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<string>("ScopeValue")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("TransportScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("OperationId");

                    b.HasIndex("ScopeHash")
                        .IsUnique();

                    b.ToTable("access_scope_destroy_receipts", "access", t =>
                        {
                            t.HasCheckConstraint("CK_access_scope_destroy_receipts_progress", "\"RemovedRecordCount\" >= 0 AND \"CompletedBatchCount\" >= 0");

                            t.HasCheckConstraint("CK_access_scope_destroy_receipts_revisions", "\"ExpectedRevision\" >= 0 AND \"ResultingRevision\" > \"ExpectedRevision\"");
                        });
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessControlScopeState", b =>
                {
                    b.Property<string>("ScopeHash")
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<Guid?>("CloseOperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CloseRequestSha256")
                        .HasMaxLength(64)
                        .HasColumnType("nchar(64)")
                        .IsFixedLength();

                    b.Property<long>("CloseRevision")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("bit");

                    b.Property<string>("ScopeValue")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("TransportScopeId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("ScopeHash");

                    b.HasIndex("TransportScopeId")
                        .IsUnique();

                    b.HasIndex("IsClosed", "ClosedAtUtc", "ScopeHash");

                    b.ToTable("access_scope_states", "access", t =>
                        {
                            t.HasCheckConstraint("CK_access_scope_states_close_revision", "\"CloseRevision\" >= 0");
                        });
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessPrincipal", b =>
                {
                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Kind", "SubjectId");

                    b.ToTable("principals", "access");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", "access");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessRolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "PermissionCode")
                        .IsUnique();

                    b.ToTable("role_permissions", "access");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessSubjectRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<long?>("ExpiresAtUnixMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<long?>("RevokedAtUnixMilliseconds")
                        .HasColumnType("bigint");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScopeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ScopeValue")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("Scope");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SubjectKind")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAtUnixMilliseconds", "RevokedAtUnixMilliseconds")
                        .HasDatabaseName("IX_role_assignments_expiry_revocation");

                    b.HasIndex("RoleId", "RevokedAtUnixMilliseconds", "ExpiresAtUnixMilliseconds")
                        .HasDatabaseName("IX_role_assignments_role_lifecycle");

                    b.HasIndex("SubjectKind", "SubjectId", "RoleId", "ScopeHash")
                        .HasDatabaseName("IX_role_assignments_subject_role_scope_hash");

                    b.HasIndex("SubjectKind", "SubjectId", "ScopeHash", "RevokedAtUnixMilliseconds", "ExpiresAtUnixMilliseconds")
                        .HasDatabaseName("IX_role_assignments_subject_scope_hash_lifecycle");

                    b.ToTable("subject_role_assignments", "access");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Domain.Entities.AccessProfileAssignment", b =>
                {
                    b.HasOne("Gma.Modules.AccessControl.Domain.Aggregates.AccessProfile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gma.Modules.AccessControl.Persistence.Entities.AccessPrincipal", null)
                        .WithMany()
                        .HasForeignKey("SubjectKind", "SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Domain.Entities.AccessProfileChange", b =>
                {
                    b.HasOne("Gma.Modules.AccessControl.Domain.Aggregates.AccessProfile", "Profile")
                        .WithMany("Changes")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Domain.Entities.AccessProfilePermission", b =>
                {
                    b.HasOne("Gma.Modules.AccessControl.Domain.Aggregates.AccessProfile", "Profile")
                        .WithMany("Permissions")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessControlScopeDestroyOperation", b =>
                {
                    b.HasOne("Gma.Modules.AccessControl.Persistence.Entities.AccessControlScopeState", null)
                        .WithOne()
                        .HasForeignKey("Gma.Modules.AccessControl.Persistence.Entities.AccessControlScopeDestroyOperation", "ScopeHash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessControlScopeDestroyPrincipalCandidate", b =>
                {
                    b.HasOne("Gma.Modules.AccessControl.Persistence.Entities.AccessControlScopeDestroyOperation", null)
                        .WithMany()
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessControlScopeDestroyReceipt", b =>
                {
                    b.HasOne("Gma.Modules.AccessControl.Persistence.Entities.AccessControlScopeState", null)
                        .WithOne()
                        .HasForeignKey("Gma.Modules.AccessControl.Persistence.Entities.AccessControlScopeDestroyReceipt", "ScopeHash")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessRolePermission", b =>
                {
                    b.HasOne("Gma.Modules.AccessControl.Persistence.Entities.AccessRole", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessSubjectRoleAssignment", b =>
                {
                    b.HasOne("Gma.Modules.AccessControl.Persistence.Entities.AccessRole", "Role")
                        .WithMany("Assignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gma.Modules.AccessControl.Persistence.Entities.AccessPrincipal", null)
                        .WithMany()
                        .HasForeignKey("SubjectKind", "SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Domain.Aggregates.AccessProfile", b =>
                {
                    b.Navigation("Changes");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessRole", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
