// <auto-generated />
using System;
using Gma.Modules.AccessControl.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gma.Modules.AccessControl.Persistence.SqlServerMigrations.Migrations
{
    [DbContext(typeof(AccessControlDbContext))]
    partial class AccessControlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("access")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessBootstrapState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("ClaimedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ClaimedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("ManagementRevision")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("bootstrap_state", "access");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ManagementRevision = 0L
                        });
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessPrincipal", b =>
                {
                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Kind", "SubjectId");

                    b.ToTable("principals", "access");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", "access");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessRolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "PermissionCode")
                        .IsUnique();

                    b.ToTable("role_permissions", "access");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessSubjectRoleAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScopeValue")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)")
                        .HasColumnName("Scope");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SubjectKind")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("SubjectKind", "SubjectId", "ScopeValue");

                    b.HasIndex("SubjectKind", "SubjectId", "RoleId", "ScopeValue")
                        .IsUnique();

                    b.ToTable("subject_role_assignments", "access");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessRolePermission", b =>
                {
                    b.HasOne("Gma.Modules.AccessControl.Persistence.Entities.AccessRole", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessSubjectRoleAssignment", b =>
                {
                    b.HasOne("Gma.Modules.AccessControl.Persistence.Entities.AccessRole", "Role")
                        .WithMany("Assignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gma.Modules.AccessControl.Persistence.Entities.AccessPrincipal", null)
                        .WithMany()
                        .HasForeignKey("SubjectKind", "SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Gma.Modules.AccessControl.Persistence.Entities.AccessRole", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
